//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RTAFMailManagement.RTAFService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RTAFMailSoap", Namespace="http://10.107.6.5/RTAFService/")]
    public partial class RTAFMail : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RTAFMail() {
            this.Url = global::RTAFMailManagement.Properties.Settings.Default.RTAFMailManagement_RTAFService_RTAFMail;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.107.6.5/RTAFService/GetData", RequestNamespace="http://10.107.6.5/RTAFService/", ResponseNamespace="http://10.107.6.5/RTAFService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RTAFMailData[] GetData(string UserName, string Password, string Unit) {
            object[] results = this.Invoke("GetData", new object[] {
                        UserName,
                        Password,
                        Unit});
            return ((RTAFMailData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(string UserName, string Password, string Unit) {
            this.GetDataAsync(UserName, Password, Unit, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(string UserName, string Password, string Unit, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        UserName,
                        Password,
                        Unit}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.107.6.5/RTAFService/")]
    public partial class RTAFMailData {
        
        private string idField;
        
        private string peopleIDField;
        
        private string rANKField;
        
        private string rANKCODEField;
        
        private string fIRSTNAMEField;
        
        private string lASTNAMEField;
        
        private string uNITCODEField;
        
        private System.DateTime bIRTHDAYField;
        
        private string uNITNAMEField;
        
        private string pOSITIONField;
        
        private string sTATUSField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string PeopleID {
            get {
                return this.peopleIDField;
            }
            set {
                this.peopleIDField = value;
            }
        }
        
        /// <remarks/>
        public string RANK {
            get {
                return this.rANKField;
            }
            set {
                this.rANKField = value;
            }
        }
        
        /// <remarks/>
        public string RANKCODE {
            get {
                return this.rANKCODEField;
            }
            set {
                this.rANKCODEField = value;
            }
        }
        
        /// <remarks/>
        public string FIRSTNAME {
            get {
                return this.fIRSTNAMEField;
            }
            set {
                this.fIRSTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string LASTNAME {
            get {
                return this.lASTNAMEField;
            }
            set {
                this.lASTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string UNITCODE {
            get {
                return this.uNITCODEField;
            }
            set {
                this.uNITCODEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BIRTHDAY {
            get {
                return this.bIRTHDAYField;
            }
            set {
                this.bIRTHDAYField = value;
            }
        }
        
        /// <remarks/>
        public string UNITNAME {
            get {
                return this.uNITNAMEField;
            }
            set {
                this.uNITNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string POSITION {
            get {
                return this.pOSITIONField;
            }
            set {
                this.pOSITIONField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RTAFMailData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTAFMailData[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591