//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RTAFMailManagement.IDG_MailService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateUserExistsMailboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisableMailboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveMailboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSizeMailboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckNumberOfMailboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumberOfMailboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSizeMailboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastLoginMailboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckMailboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDistributionGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMembertoDistributionGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveDistributionGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDistributionGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeStatusDistributionGroupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::RTAFMailManagement.Properties.Settings.Default.RTAFMailManagement_IDG_MailService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateUserExistsMailboxCompletedEventHandler CreateUserExistsMailboxCompleted;
        
        /// <remarks/>
        public event DisableMailboxCompletedEventHandler DisableMailboxCompleted;
        
        /// <remarks/>
        public event MoveMailboxCompletedEventHandler MoveMailboxCompleted;
        
        /// <remarks/>
        public event GetSizeMailboxCompletedEventHandler GetSizeMailboxCompleted;
        
        /// <remarks/>
        public event CheckNumberOfMailboxCompletedEventHandler CheckNumberOfMailboxCompleted;
        
        /// <remarks/>
        public event GetNumberOfMailboxCompletedEventHandler GetNumberOfMailboxCompleted;
        
        /// <remarks/>
        public event SetSizeMailboxCompletedEventHandler SetSizeMailboxCompleted;
        
        /// <remarks/>
        public event GetLastLoginMailboxCompletedEventHandler GetLastLoginMailboxCompleted;
        
        /// <remarks/>
        public event CheckMailboxCompletedEventHandler CheckMailboxCompleted;
        
        /// <remarks/>
        public event CreateDistributionGroupCompletedEventHandler CreateDistributionGroupCompleted;
        
        /// <remarks/>
        public event AddMembertoDistributionGroupCompletedEventHandler AddMembertoDistributionGroupCompleted;
        
        /// <remarks/>
        public event RemoveDistributionGroupCompletedEventHandler RemoveDistributionGroupCompleted;
        
        /// <remarks/>
        public event CheckDistributionGroupCompletedEventHandler CheckDistributionGroupCompleted;
        
        /// <remarks/>
        public event ChangeStatusDistributionGroupCompletedEventHandler ChangeStatusDistributionGroupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateUserExistsMailbox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateUserExistsMailbox(string pidentity, string pdatabase, string palias) {
            object[] results = this.Invoke("CreateUserExistsMailbox", new object[] {
                        pidentity,
                        pdatabase,
                        palias});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUserExistsMailboxAsync(string pidentity, string pdatabase, string palias) {
            this.CreateUserExistsMailboxAsync(pidentity, pdatabase, palias, null);
        }
        
        /// <remarks/>
        public void CreateUserExistsMailboxAsync(string pidentity, string pdatabase, string palias, object userState) {
            if ((this.CreateUserExistsMailboxOperationCompleted == null)) {
                this.CreateUserExistsMailboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserExistsMailboxOperationCompleted);
            }
            this.InvokeAsync("CreateUserExistsMailbox", new object[] {
                        pidentity,
                        pdatabase,
                        palias}, this.CreateUserExistsMailboxOperationCompleted, userState);
        }
        
        private void OnCreateUserExistsMailboxOperationCompleted(object arg) {
            if ((this.CreateUserExistsMailboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserExistsMailboxCompleted(this, new CreateUserExistsMailboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisableMailbox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DisableMailbox(string pidentity) {
            object[] results = this.Invoke("DisableMailbox", new object[] {
                        pidentity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DisableMailboxAsync(string pidentity) {
            this.DisableMailboxAsync(pidentity, null);
        }
        
        /// <remarks/>
        public void DisableMailboxAsync(string pidentity, object userState) {
            if ((this.DisableMailboxOperationCompleted == null)) {
                this.DisableMailboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisableMailboxOperationCompleted);
            }
            this.InvokeAsync("DisableMailbox", new object[] {
                        pidentity}, this.DisableMailboxOperationCompleted, userState);
        }
        
        private void OnDisableMailboxOperationCompleted(object arg) {
            if ((this.DisableMailboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisableMailboxCompleted(this, new DisableMailboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MoveMailbox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MoveMailbox(string pidentity, string pTargetdatabase) {
            object[] results = this.Invoke("MoveMailbox", new object[] {
                        pidentity,
                        pTargetdatabase});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MoveMailboxAsync(string pidentity, string pTargetdatabase) {
            this.MoveMailboxAsync(pidentity, pTargetdatabase, null);
        }
        
        /// <remarks/>
        public void MoveMailboxAsync(string pidentity, string pTargetdatabase, object userState) {
            if ((this.MoveMailboxOperationCompleted == null)) {
                this.MoveMailboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveMailboxOperationCompleted);
            }
            this.InvokeAsync("MoveMailbox", new object[] {
                        pidentity,
                        pTargetdatabase}, this.MoveMailboxOperationCompleted, userState);
        }
        
        private void OnMoveMailboxOperationCompleted(object arg) {
            if ((this.MoveMailboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveMailboxCompleted(this, new MoveMailboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSizeMailbox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetSizeMailbox(string psize) {
            object[] results = this.Invoke("GetSizeMailbox", new object[] {
                        psize});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetSizeMailboxAsync(string psize) {
            this.GetSizeMailboxAsync(psize, null);
        }
        
        /// <remarks/>
        public void GetSizeMailboxAsync(string psize, object userState) {
            if ((this.GetSizeMailboxOperationCompleted == null)) {
                this.GetSizeMailboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSizeMailboxOperationCompleted);
            }
            this.InvokeAsync("GetSizeMailbox", new object[] {
                        psize}, this.GetSizeMailboxOperationCompleted, userState);
        }
        
        private void OnGetSizeMailboxOperationCompleted(object arg) {
            if ((this.GetSizeMailboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSizeMailboxCompleted(this, new GetSizeMailboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckNumberOfMailbox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckNumberOfMailbox(string pDatabase, int pNumberOfMailbox) {
            object[] results = this.Invoke("CheckNumberOfMailbox", new object[] {
                        pDatabase,
                        pNumberOfMailbox});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckNumberOfMailboxAsync(string pDatabase, int pNumberOfMailbox) {
            this.CheckNumberOfMailboxAsync(pDatabase, pNumberOfMailbox, null);
        }
        
        /// <remarks/>
        public void CheckNumberOfMailboxAsync(string pDatabase, int pNumberOfMailbox, object userState) {
            if ((this.CheckNumberOfMailboxOperationCompleted == null)) {
                this.CheckNumberOfMailboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckNumberOfMailboxOperationCompleted);
            }
            this.InvokeAsync("CheckNumberOfMailbox", new object[] {
                        pDatabase,
                        pNumberOfMailbox}, this.CheckNumberOfMailboxOperationCompleted, userState);
        }
        
        private void OnCheckNumberOfMailboxOperationCompleted(object arg) {
            if ((this.CheckNumberOfMailboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckNumberOfMailboxCompleted(this, new CheckNumberOfMailboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumberOfMailbox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNumberOfMailbox(string pDatabase) {
            object[] results = this.Invoke("GetNumberOfMailbox", new object[] {
                        pDatabase});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumberOfMailboxAsync(string pDatabase) {
            this.GetNumberOfMailboxAsync(pDatabase, null);
        }
        
        /// <remarks/>
        public void GetNumberOfMailboxAsync(string pDatabase, object userState) {
            if ((this.GetNumberOfMailboxOperationCompleted == null)) {
                this.GetNumberOfMailboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumberOfMailboxOperationCompleted);
            }
            this.InvokeAsync("GetNumberOfMailbox", new object[] {
                        pDatabase}, this.GetNumberOfMailboxOperationCompleted, userState);
        }
        
        private void OnGetNumberOfMailboxOperationCompleted(object arg) {
            if ((this.GetNumberOfMailboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumberOfMailboxCompleted(this, new GetNumberOfMailboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetSizeMailbox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetSizeMailbox(string pUserName, string pSize) {
            object[] results = this.Invoke("SetSizeMailbox", new object[] {
                        pUserName,
                        pSize});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetSizeMailboxAsync(string pUserName, string pSize) {
            this.SetSizeMailboxAsync(pUserName, pSize, null);
        }
        
        /// <remarks/>
        public void SetSizeMailboxAsync(string pUserName, string pSize, object userState) {
            if ((this.SetSizeMailboxOperationCompleted == null)) {
                this.SetSizeMailboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSizeMailboxOperationCompleted);
            }
            this.InvokeAsync("SetSizeMailbox", new object[] {
                        pUserName,
                        pSize}, this.SetSizeMailboxOperationCompleted, userState);
        }
        
        private void OnSetSizeMailboxOperationCompleted(object arg) {
            if ((this.SetSizeMailboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSizeMailboxCompleted(this, new SetSizeMailboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastLoginMailbox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetLastLoginMailbox(string pDatabase, string lastloginmonths, string order) {
            object[] results = this.Invoke("GetLastLoginMailbox", new object[] {
                        pDatabase,
                        lastloginmonths,
                        order});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastLoginMailboxAsync(string pDatabase, string lastloginmonths, string order) {
            this.GetLastLoginMailboxAsync(pDatabase, lastloginmonths, order, null);
        }
        
        /// <remarks/>
        public void GetLastLoginMailboxAsync(string pDatabase, string lastloginmonths, string order, object userState) {
            if ((this.GetLastLoginMailboxOperationCompleted == null)) {
                this.GetLastLoginMailboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastLoginMailboxOperationCompleted);
            }
            this.InvokeAsync("GetLastLoginMailbox", new object[] {
                        pDatabase,
                        lastloginmonths,
                        order}, this.GetLastLoginMailboxOperationCompleted, userState);
        }
        
        private void OnGetLastLoginMailboxOperationCompleted(object arg) {
            if ((this.GetLastLoginMailboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastLoginMailboxCompleted(this, new GetLastLoginMailboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckMailbox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckMailbox(string email) {
            object[] results = this.Invoke("CheckMailbox", new object[] {
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckMailboxAsync(string email) {
            this.CheckMailboxAsync(email, null);
        }
        
        /// <remarks/>
        public void CheckMailboxAsync(string email, object userState) {
            if ((this.CheckMailboxOperationCompleted == null)) {
                this.CheckMailboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckMailboxOperationCompleted);
            }
            this.InvokeAsync("CheckMailbox", new object[] {
                        email}, this.CheckMailboxOperationCompleted, userState);
        }
        
        private void OnCheckMailboxOperationCompleted(object arg) {
            if ((this.CheckMailboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckMailboxCompleted(this, new CheckMailboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateDistributionGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateDistributionGroup(string name, string OrganizationalUnit) {
            object[] results = this.Invoke("CreateDistributionGroup", new object[] {
                        name,
                        OrganizationalUnit});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDistributionGroupAsync(string name, string OrganizationalUnit) {
            this.CreateDistributionGroupAsync(name, OrganizationalUnit, null);
        }
        
        /// <remarks/>
        public void CreateDistributionGroupAsync(string name, string OrganizationalUnit, object userState) {
            if ((this.CreateDistributionGroupOperationCompleted == null)) {
                this.CreateDistributionGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDistributionGroupOperationCompleted);
            }
            this.InvokeAsync("CreateDistributionGroup", new object[] {
                        name,
                        OrganizationalUnit}, this.CreateDistributionGroupOperationCompleted, userState);
        }
        
        private void OnCreateDistributionGroupOperationCompleted(object arg) {
            if ((this.CreateDistributionGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDistributionGroupCompleted(this, new CreateDistributionGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMembertoDistributionGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddMembertoDistributionGroup(string Identity, string Member) {
            object[] results = this.Invoke("AddMembertoDistributionGroup", new object[] {
                        Identity,
                        Member});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddMembertoDistributionGroupAsync(string Identity, string Member) {
            this.AddMembertoDistributionGroupAsync(Identity, Member, null);
        }
        
        /// <remarks/>
        public void AddMembertoDistributionGroupAsync(string Identity, string Member, object userState) {
            if ((this.AddMembertoDistributionGroupOperationCompleted == null)) {
                this.AddMembertoDistributionGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMembertoDistributionGroupOperationCompleted);
            }
            this.InvokeAsync("AddMembertoDistributionGroup", new object[] {
                        Identity,
                        Member}, this.AddMembertoDistributionGroupOperationCompleted, userState);
        }
        
        private void OnAddMembertoDistributionGroupOperationCompleted(object arg) {
            if ((this.AddMembertoDistributionGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMembertoDistributionGroupCompleted(this, new AddMembertoDistributionGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveDistributionGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveDistributionGroup(string Identity) {
            object[] results = this.Invoke("RemoveDistributionGroup", new object[] {
                        Identity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveDistributionGroupAsync(string Identity) {
            this.RemoveDistributionGroupAsync(Identity, null);
        }
        
        /// <remarks/>
        public void RemoveDistributionGroupAsync(string Identity, object userState) {
            if ((this.RemoveDistributionGroupOperationCompleted == null)) {
                this.RemoveDistributionGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveDistributionGroupOperationCompleted);
            }
            this.InvokeAsync("RemoveDistributionGroup", new object[] {
                        Identity}, this.RemoveDistributionGroupOperationCompleted, userState);
        }
        
        private void OnRemoveDistributionGroupOperationCompleted(object arg) {
            if ((this.RemoveDistributionGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveDistributionGroupCompleted(this, new RemoveDistributionGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDistributionGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckDistributionGroup(string email) {
            object[] results = this.Invoke("CheckDistributionGroup", new object[] {
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckDistributionGroupAsync(string email) {
            this.CheckDistributionGroupAsync(email, null);
        }
        
        /// <remarks/>
        public void CheckDistributionGroupAsync(string email, object userState) {
            if ((this.CheckDistributionGroupOperationCompleted == null)) {
                this.CheckDistributionGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDistributionGroupOperationCompleted);
            }
            this.InvokeAsync("CheckDistributionGroup", new object[] {
                        email}, this.CheckDistributionGroupOperationCompleted, userState);
        }
        
        private void OnCheckDistributionGroupOperationCompleted(object arg) {
            if ((this.CheckDistributionGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDistributionGroupCompleted(this, new CheckDistributionGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeStatusDistributionGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangeStatusDistributionGroup(string Identity, bool status) {
            object[] results = this.Invoke("ChangeStatusDistributionGroup", new object[] {
                        Identity,
                        status});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeStatusDistributionGroupAsync(string Identity, bool status) {
            this.ChangeStatusDistributionGroupAsync(Identity, status, null);
        }
        
        /// <remarks/>
        public void ChangeStatusDistributionGroupAsync(string Identity, bool status, object userState) {
            if ((this.ChangeStatusDistributionGroupOperationCompleted == null)) {
                this.ChangeStatusDistributionGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeStatusDistributionGroupOperationCompleted);
            }
            this.InvokeAsync("ChangeStatusDistributionGroup", new object[] {
                        Identity,
                        status}, this.ChangeStatusDistributionGroupOperationCompleted, userState);
        }
        
        private void OnChangeStatusDistributionGroupOperationCompleted(object arg) {
            if ((this.ChangeStatusDistributionGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeStatusDistributionGroupCompleted(this, new ChangeStatusDistributionGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateUserExistsMailboxCompletedEventHandler(object sender, CreateUserExistsMailboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUserExistsMailboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUserExistsMailboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DisableMailboxCompletedEventHandler(object sender, DisableMailboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisableMailboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisableMailboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void MoveMailboxCompletedEventHandler(object sender, MoveMailboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveMailboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MoveMailboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetSizeMailboxCompletedEventHandler(object sender, GetSizeMailboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSizeMailboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSizeMailboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckNumberOfMailboxCompletedEventHandler(object sender, CheckNumberOfMailboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckNumberOfMailboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckNumberOfMailboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetNumberOfMailboxCompletedEventHandler(object sender, GetNumberOfMailboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumberOfMailboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumberOfMailboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SetSizeMailboxCompletedEventHandler(object sender, SetSizeMailboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSizeMailboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSizeMailboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetLastLoginMailboxCompletedEventHandler(object sender, GetLastLoginMailboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastLoginMailboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastLoginMailboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckMailboxCompletedEventHandler(object sender, CheckMailboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckMailboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckMailboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateDistributionGroupCompletedEventHandler(object sender, CreateDistributionGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDistributionGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDistributionGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddMembertoDistributionGroupCompletedEventHandler(object sender, AddMembertoDistributionGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMembertoDistributionGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMembertoDistributionGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RemoveDistributionGroupCompletedEventHandler(object sender, RemoveDistributionGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveDistributionGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveDistributionGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckDistributionGroupCompletedEventHandler(object sender, CheckDistributionGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDistributionGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDistributionGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChangeStatusDistributionGroupCompletedEventHandler(object sender, ChangeStatusDistributionGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeStatusDistributionGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeStatusDistributionGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591