//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTAFMailManagement.Form_ComparePersonData
{


    public partial class Form_Search_PersonData
    {

        /// <summary>
        /// Units_Lbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Units_Lbl;

        /// <summary>
        /// Units_DDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Units_DDL;

        /// <summary>
        /// Search_rtaf_data_Btn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton Search_rtaf_data_Btn;

        /// <summary>
        /// page_tab_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RTAFMailManagement.Form_ComparePersonData.Form_Display_Data_Service page_tab_1;

        /// <summary>
        /// page_tab_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RTAFMailManagement.Form_ComparePersonData.Form_Display_Data_DB page_tab_2;

        /// <summary>
        /// page_tab_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RTAFMailManagement.Form_ComparePersonData.Form_Display_Data_Compare page_tab_3;

        /// <summary>
        /// page_tab_4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RTAFMailManagement.Form_ComparePersonData.Form_Display_Data_Import page_tab_4;
    }
}
